// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCfJOKcn8E1y0H0ybdQz3LnB_DLHbiBA1U',
    appId: '1:100507319008:web:cd51edef8b800b3546ee85',
    messagingSenderId: '100507319008',
    projectId: 'rentalcontrol-e6e10',
    authDomain: 'rentalcontrol-e6e10.firebaseapp.com',
    storageBucket: 'rentalcontrol-e6e10.firebasestorage.app',
    measurementId: 'G-9EQT2RP9YB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxFNzSJazDsMv5cSSpEEMm9Hoz5rIXHKs',
    appId: '1:100507319008:android:1bb0a9c4283d088546ee85',
    messagingSenderId: '100507319008',
    projectId: 'rentalcontrol-e6e10',
    storageBucket: 'rentalcontrol-e6e10.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWS8UmfOv6o6-qofQjeg0OjvKBt-uBaJ0',
    appId: '1:100507319008:ios:16e468311a161c2746ee85',
    messagingSenderId: '100507319008',
    projectId: 'rentalcontrol-e6e10',
    storageBucket: 'rentalcontrol-e6e10.firebasestorage.app',
    iosBundleId: 'felix.davy.rentcontrol',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWS8UmfOv6o6-qofQjeg0OjvKBt-uBaJ0',
    appId: '1:100507319008:ios:16e468311a161c2746ee85',
    messagingSenderId: '100507319008',
    projectId: 'rentalcontrol-e6e10',
    storageBucket: 'rentalcontrol-e6e10.firebasestorage.app',
    iosBundleId: 'felix.davy.rentcontrol',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCfJOKcn8E1y0H0ybdQz3LnB_DLHbiBA1U',
    appId: '1:100507319008:web:04efe3935df1fe7146ee85',
    messagingSenderId: '100507319008',
    projectId: 'rentalcontrol-e6e10',
    authDomain: 'rentalcontrol-e6e10.firebaseapp.com',
    storageBucket: 'rentalcontrol-e6e10.firebasestorage.app',
    measurementId: 'G-0LB6LT1GSN',
  );
}
